{
 "title": "Istio Proxy Performance",
 "tags": [
  "istio",
  "proxy"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Proxy Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Istio-proxy Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{container=\"istio-proxy\", namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Istio-proxy container vCPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{container=\"istio-proxy\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(50, sum by(pod) (envoy_cluster_upstream_cx_active{namespace=~\"$namespace\"}))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Active Clusters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_cluster_manager_active_clusters{namespace=~\"$namespace\"})",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Throttled Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container_name!=\"POD\", image=\"\", namespace=~\"$namespace\"}[5m]) > 0",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Active Listeners",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "expr": "sum (envoy_listener_manager_total_listeners_active{namespace=~\"$namespace\"})by(pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Envoy Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Envoy Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_allocated{namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Envoy Memory Heap",
   "type": "timeseries",
   "description": "A metric to relate the amount of memory consumed by each proxy to the number of clusters it has",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_heap_size{namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Per Cluster (Expirimental)",
   "type": "timeseries",
   "description": "A metric to relate the amount of memory consumed by each proxy to the number of clusters it has",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{container=\"istio-proxy\", namespace=~\"$namespace\"}) / sum by(pod) (envoy_cluster_manager_active_clusters{namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Envoy Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Envoy Details",
   "type": "graph",
   "description": "Shows details about Envoy proxies in the mesh",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Connections"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_connect_fail{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Connection Failures"
    },
    {
     "expr": "sum(increase(envoy_server_hot_restart_epoch[1m]))",
     "legendFormat": "Envoy Restarts"
    }
   ]
  }
 ]
}