apiVersion: mesh.demo/v1
kind: Profile
metadata:
  name: eks-single-cluster-mesh-with-calico
  description: Single-cluster ambient mesh with Calico

spec:
  infra: eks-single-cluster
  environment: aws-dev

  mesh:
    istioVersion: 1.30.3
    gatewayApiVersion: v1.5.0
    profile: ambient

    image:
      istioRepo: us-docker.pkg.dev/soloio-img/istio
      helmIstioRepo: us-docker.pkg.dev/soloio-img/istio-helm
      tag: 1.30.3-solo

    components:
      - base
      - name: istiod
        values:
          global:
            network: "{{cluster.name}}"
          meshConfig:
            accessLogFile: /dev/stdout
            defaultConfig:
              proxyMetadata:
                ISTIO_META_DNS_CAPTURE: "true"
          env:
            PILOT_ENABLE_IP_AUTOALLOCATE: "true"
          pilot:
            cni:
              namespace: istio-system
              enabled: true
      - cni
      - name: ztunnel
        values:
          env:
            ISTIO_META_DNS_CAPTURE: "true"
          network: "{{cluster.name}}"

  addons:
    - name: calico
      description: Tigera-operator-installed Calico
      version: 3.32.1
      mode: chaining
      chainingTarget: AmazonVPC
      kubernetesProvider: EKS
