apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: solo-ui-tls
  namespace: istio-system
spec:
  secretName: solo-ui-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - example.com
