apiVersion: mesh.demo/v1
kind: InfraProfile
metadata:
  name: aks-single-cluster
  description: Single AKS cluster

spec:
  provider: aks
  region: Australia East
  settings:
    nodes: 2
    node_type: Standard_D2_v2

  clusters:
    - name: demo
      role: management
