apiVersion: mesh.demo/v1
kind: InfraProfile
metadata:
  name: eks-multi-cluster-ipv6
  description: EKS multi-cluster IPv6 clusters (east, west)

spec:
  name: indigo
  provider: eks-ipv6
  environment: aws-dev

  settings:
    enable_bastion: true
    enable_dns64: true
    node_type: t3.medium
    nodes: 2

  clusters:
    - name: east
      role: workload
    - name: west
      role: workload