apiVersion: mesh.demo/v1
kind: InfraProfile
metadata:
  name: eks-multi-cluster
  description: EKS multi-cluster setup (east, west)

spec:
  name: maple
  provider: eks
  environment: aws-dev

  settings:
    nodes:
      desired: 3
      type: t3.xlarge

  clusters:
    - name: east
      role: workload
    - name: west
      role: workload

  vms:
    - name: vm1
      role: workload
      cluster: east
