apiVersion: mesh.demo/v1
kind: InfraProfile
metadata:
  name: gke-multi-cluster
  description: GKE multi-cluster setup (management, east, west)

spec:
  provider: gke
  region: us-west1
  settings:
    nodes: 2
    node_type: n1-standard-2

  clusters:
    - name: east
      role: workload
    - name: west
      role: workload
