apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: authorization-policy
  namespace: default
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/default/sa/default
