apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
        version: v1
    spec:
      serviceAccountName: curl
      containers:
        - name: curl
          image: docker.io/curlimages/curl:8.11.0
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
